//array de productos - objetos literales
const items = [
    { 
        id:1,
        nombre: "Sillon Portofino un cuerpo",
        precio: 90000,
        color: "beige",
        tela: "chenille",
        cuerpos: 1,
        foto: "https://desillas.com/img/productos/ZDHGWA_12.jpg",
    },
    { 
        id:2,
        nombre: "Sillon Milan un cuerpo",
        precio: 90000,
        color: "gris",
        tela: "chenille",
        cuerpos: 1,
        foto:"https://desillas.com/img/productos/ABENPU_2.jpg",
    },
    { 
        id:3,
        nombre: "Sillon Bergamo dos cuerpos",
        precio: 120000,
        color: "beige",
        tela: "pana",
        cuerpos: 2,
        foto:"https://desillas.com/img/productos/GLTRFK_11.jpg",
    },
    { 
        id:4,
        nombre: "Sillon Parma dos cuerpos",
        precio: 120000,
        color: "rosa",
        tela: "pana",
        cuerpos: 2,
        foto:"https://desillas.com/img/productos/CJFLRK_2.jpg",
    },
    { 
        id:5,
        nombre: "Sillon Chesterfield tres cuerpos",
        precio: 160000,
        color: "beige",
        tela: "lino",
        cuerpos: 3,
        foto: "https://desillas.com/img/productos/CTZXXC_6.jpg"
    },
    { 
        id:6,
        nombre: "Sillon Savona tres cuerpos",
        precio: 160000,
        color: "beige",
        tela: "lino",
        cuerpos: 3,
        foto: "https://desillas.com/img/productos/FHFCIY_1.jpg"
    },
    { 
        id:7,
        nombre: "Silla Jeffrey",
        precio: 50000,
        color: "negro",
        tela: "cuero",
        cuerpos: 1,
        foto:"https://desillas.com/img/productos/RPLJFO_1.jpg",
    },
    { 
        id:8,
        nombre: "Silla Charles",
        precio: 38000,
        color: "blanco",
        tela: "lino",
        cuerpos: 1,
        foto:"https://desillas.com/img/productos/PEYUWG_1.jpg",
    }
];